### ISSUE TITLE
Support for gulp

### ISSUE THREAD

**Issue by redmile** [bq/penguin#2]
Hi, very nice project, compliments! :+1: 

Is it possible to add support for gulp?

**Comment by oscarferrandiz-zz** [comment]
Hi @redmile !

Thanks for your support, we really appreciate it :) We're so glad you like our project.

Although Penguin building process uses Grunt, it has been designed and developed to being used with any other task runner (such as Gulp or Broccoli) or building process. Inside your project you can directly reffer the .scss and .js files placed inside /src folder that you want to include. For example, this is how your application main.scss should look like:

```
// Base: Variables
@import "path_to_penguin/src/base/_variables";
@import "path_to_theme/base/_variables";

// Components: Variables
@import "path_to_penguin/src/components/_variables";
@import "path_to_theme/components/_variables";

// Base: Scaffolding
@import "path_to_penguin/src/base/_scaffolding";
@import "path_to_theme/base/_scaffolding";

// Base: Mixins
@import "path_to_penguin/src/base/_mixins";

// Base: Reset
@import "path_to_penguin/src/base/_reset";

// Base: Print
@import "path_to_penguin/src/base/_print";

// Base: Utils
@import "path_to_penguin/src/base/_utils";

// Base: Responsive utilities
@import "path_to_penguin/src/base/_responsive";

// Base: Grid system
@import "path_to_penguin/src/base/_grid";

// Components: Animations
@import "path_to_penguin/src/base/_animations";

// Components: Alert
@import "path_to_penguin/src/components/alert";
@import "path_to_theme/components/alert";

// Components: Text
@import "path_to_penguin/src/components/text";
@import "path_to_theme/components/text";

[...]

```

Now you just have to compile that main.scss using your favourite method and voilà! :)

We hope this answers your question.

Cheers!

**Comment by redmile** [comment]
@oscarferrandiz Thanks for the quick reply! :)
